/**
 * cronozen-dpu init
 *
 * DPU 프로젝트 초기화. dpu.config.yaml을 생성합니다.
 */

import { writeFileSync, existsSync } from 'fs';
import { join } from 'path';

const DEFAULT_CONFIG = `# Cronozen DPU Configuration
# Generated by: cronozen-dpu init

dpu:
  # 기본 도메인 (조직/서비스 식별자)
  domain: "my-organization"

  # 기본 Evidence Level (DRAFT | PARTIAL | AUDIT_READY)
  default_evidence_level: "DRAFT"

  # 해시 체인 활성화
  hash_chain: true

  # 기능 플래그
  features:
    # 기본 기능 (Core)
    hash_chain: true
    schema_validation: true

    # Pro 기능 (라이선스 필요)
    # governance_guards: false
    # compliance_report: false
    # responsibility_graph: false

# 스토리지 어댑터 설정
storage:
  # adapter: "prisma" | "postgres" | "sqlite" | "memory"
  adapter: "memory"

  # Prisma 사용 시
  # prisma:
  #   database_url: "postgresql://..."
`;

export async function init(): Promise<void> {
  const configPath = join(process.cwd(), 'dpu.config.yaml');

  if (existsSync(configPath)) {
    console.log('dpu.config.yaml already exists. Skipping.');
    return;
  }

  writeFileSync(configPath, DEFAULT_CONFIG, 'utf-8');
  console.log('Created dpu.config.yaml');
  console.log('');
  console.log('Next steps:');
  console.log('  1. Edit dpu.config.yaml to set your domain');
  console.log('  2. Install a storage adapter: npm install @cronozen/dpu-connector-prisma');
  console.log('  3. Run: cronozen-dpu validate');
}
